[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["rm -rf node_modules/.cache", "npm install --prefer-offline --no-audit"]

[phases.build]
cmds = ["rm -rf node_modules/.cache", "npm run build"]

[start]
cmd = "npm start"
